"""Clustering muddiest-point answers into themes for the teacher.

The one place a model is used in Part B, and the boundary is absolute:

* **The model sees anonymous strings.** Not names, not emails, not fellow ids,
  not counts per person, not attendance, not confidence scores. The payload is a
  numbered list of sentences and nothing else, and there is a test that asserts
  it.
* **No AI ever judges an individual fellow's free text.** Gemini's only job here
  is grouping *content* into themes — about the lesson, never about a person. It
  does not classify takeaway quality, does not score effort, does not flag
  anyone, and never touches the help-request table.
* **Degrade rather than crash.** No key or no network means no themes and a
  clear message. A pipeline that fails because an optional enrichment was
  unavailable has made the enrichment mandatory.

**Why this matters more than it looks.** Closing the loop — showing fellows what
their confusion actually changed about the teaching — is the highest-leverage
trust move in the project. It is what makes the form visibly *for* them rather
than *about* them, and research on youth data collection is consistent that this
is what drives honest responding.

The teacher-facing view is built. The fellow-facing view is **not** — that is a
decision for the data owner, not a default.
"""

from __future__ import annotations

import json
import random
import time
from dataclasses import dataclass, field
from typing import Any, Protocol, Sequence

import psycopg

from .config import Settings, get_settings
from .db import execute, fetch_all, fetch_one
from .errors import AiUnavailable
from .logging_setup import get_logger
from .rotation import MUDDIEST_POINT

log = get_logger(__name__)

# Bump whenever the prompt text or the schema changes. Stored on every row, so a
# theme generated by a different prompt is distinguishable months later rather
# than silently comparable.
PROMPT_VERSION = "b1"

MIN_THEMES = 2
MAX_THEMES = 5

#: Below this many answers, clustering is noise. Two sentences do not have a
#: theme; they have two sentences, and a model asked to find structure in them
#: will invent some.
MIN_ANSWERS = 3

RESPONSE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "themes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "label": {"type": "string"},
                    "summary": {"type": "string"},
                    "answer_numbers": {"type": "array", "items": {"type": "integer"}},
                },
                "required": ["label", "summary", "answer_numbers"],
            },
        }
    },
    "required": ["themes"],
}

PROMPT_TEMPLATE = """\
Below are anonymous answers from students to the question "What's still unclear?" \
after one lesson. Group them into {min_themes} to {max_themes} themes so the \
teacher can see what to revisit.

Answers:
{answers}

Rules:
- Group by SUBJECT MATTER — what the students are confused about.
- Do not comment on how well written any answer is.
- Do not describe or characterise any student. These are anonymous strings and \
you know nothing about who wrote them.
- Every answer number belongs to exactly one theme.
- A label is at most six words. A summary is exactly one sentence, describing \
the confusion, not the students.
- If the answers genuinely have no shared subject, return one theme per distinct \
subject rather than forcing them together.

Reply with JSON only: themes, each with label, summary, and answer_numbers \
(the numbers shown above).\
"""


@dataclass(frozen=True)
class ThemeDraft:
    """One theme as the model returned it, before it is stored."""

    label: str
    summary: str
    #: 1-based positions in the list the model was shown.
    answer_numbers: tuple[int, ...] = ()


@dataclass
class ThemeResult:
    """What one clustering run produced, or why it produced nothing."""

    session_id: str
    themes: list[dict[str, Any]] = field(default_factory=list)
    answers_considered: int = 0
    generated: bool = False
    message: str = ""
    superseded: int = 0


class Clusterer(Protocol):
    """What ``generate_themes`` needs. Injectable so tests never hit a network."""

    model_name: str
    prompt_version: str

    def cluster(self, texts: Sequence[str]) -> list[ThemeDraft]:
        ...


def build_prompt(texts: Sequence[str]) -> str:
    """The exact string sent to the model.

    A separate, pure function so a test can assert what leaves this process
    without mocking a client. Everything the model is told is in the return value
    of this function.
    """
    numbered = "\n".join(f"{index}. {text.strip()}" for index, text in enumerate(texts, start=1))
    return PROMPT_TEMPLATE.format(
        min_themes=MIN_THEMES, max_themes=MAX_THEMES, answers=numbered
    )


class GeminiClusterer:
    """The live clusterer.

    Uses ``google-genai`` (``from google import genai``), the same package and
    the same conventions as Part A's tier 2: ``gemini-2.5-flash`` by default,
    ``temperature=0``, a response schema, and backoff on 429.
    """

    prompt_version = PROMPT_VERSION

    def __init__(self, settings: Settings | None = None) -> None:
        settings = settings or get_settings()
        if not settings.gemini_api_key:
            raise AiUnavailable(
                "GEMINI_API_KEY is not set, so muddiest-point themes cannot be "
                "generated. This is not fatal: the answers are stored and readable, "
                "there is simply no clustering over them."
            )
        try:
            from google import genai
        except ImportError as exc:  # pragma: no cover - dependency is declared
            raise AiUnavailable(f"google-genai is not importable: {exc}") from exc

        self._client = genai.Client(api_key=settings.gemini_api_key)
        self.model_name = settings.ai_model

    def cluster(self, texts: Sequence[str]) -> list[ThemeDraft]:
        from google.genai import types

        prompt = build_prompt(texts)
        config = types.GenerateContentConfig(
            # The same answers must cluster the same way twice, or "regenerate"
            # would mean "reshuffle" and a teacher could never tell whether the
            # lesson changed or the model did.
            temperature=0,
            response_mime_type="application/json",
            response_schema=types.Schema(**RESPONSE_SCHEMA),
        )

        last_error: Exception | None = None
        for attempt in range(4):
            try:
                response = self._client.models.generate_content(
                    model=self.model_name, contents=prompt, config=config
                )
                return parse_themes(response.text, len(texts))
            except AiUnavailable:
                raise
            except Exception as exc:  # noqa: BLE001 - classified below
                last_error = exc
                if _is_rate_limit(exc) and attempt < 3:
                    delay = min(2**attempt, 16) * (0.5 + random.random() / 2)
                    log.warning("gemini rate limited; retrying in %.1fs", delay)
                    time.sleep(delay)
                    continue
                break

        raise AiUnavailable(f"Gemini call failed: {last_error}") from last_error


def _is_rate_limit(exc: Exception) -> bool:
    text = str(exc).lower()
    return "429" in text or "resource_exhausted" in text or "rate limit" in text


def parse_themes(text: str | None, answer_count: int) -> list[ThemeDraft]:
    """Turn the model's JSON into drafts, discarding numbers it invented.

    An answer number outside the range shown is dropped rather than trusted: a
    model that hallucinates an index would otherwise attach a theme to whichever
    answer happened to sit at that position.
    """
    if not text:
        raise AiUnavailable("Gemini returned an empty response")
    try:
        payload = json.loads(text)
    except ValueError as exc:
        raise AiUnavailable(f"Gemini returned non-JSON: {text[:200]!r}") from exc

    drafts: list[ThemeDraft] = []
    for raw in payload.get("themes") or []:
        label = str(raw.get("label", "")).strip()
        summary = str(raw.get("summary", "")).strip()
        numbers = tuple(
            sorted(
                {
                    int(n)
                    for n in (raw.get("answer_numbers") or [])
                    if isinstance(n, int) and 1 <= int(n) <= answer_count
                }
            )
        )
        if label:
            drafts.append(ThemeDraft(label=label, summary=summary, answer_numbers=numbers))
    if not drafts:
        raise AiUnavailable("Gemini returned no usable themes")
    return drafts


def build_clusterer(settings: Settings | None = None) -> Clusterer | None:
    """A live clusterer, or None when clustering cannot run.

    None rather than an exception: a missing API key is a configuration state,
    not a failure of this run, and the caller degrades to "no themes".
    """
    settings = settings or get_settings()
    try:
        return GeminiClusterer(settings)
    except AiUnavailable as exc:
        log.info("theme clustering unavailable: %s", str(exc).splitlines()[0])
        return None


def muddiest_answers(conn: psycopg.Connection, session_id: str) -> list[dict[str, Any]]:
    """The answers eligible for clustering: text and row id, nothing else.

    The SELECT list is the privacy boundary. It deliberately does not fetch the
    email or the fellow, so there is no identifying field in scope for a later
    edit to accidentally include in the payload.
    """
    return fetch_all(
        conn,
        """
        select checkin_b_id, rotating_text
          from checkin_b
         where session_id = %s
           and rotating_kind = %s
           and btrim(coalesce(rotating_text, '')) <> ''
         order by submitted_at_utc, checkin_b_id
        """,
        (session_id, MUDDIEST_POINT),
    )


def current_themes(conn: psycopg.Connection, session_id: str) -> list[dict[str, Any]]:
    """The live themes for one session, with their member answers attached."""
    themes = fetch_all(
        conn,
        """
        select theme_id, label, summary, model, prompt_version, generated_at
          from muddiest_theme
         where session_id = %s and superseded_at is null
         order by generated_at desc, label
        """,
        (session_id,),
    )
    for theme in themes:
        theme["members"] = fetch_all(
            conn,
            """
            select b.checkin_b_id, b.rotating_text
              from muddiest_theme_member m
              join checkin_b b on b.checkin_b_id = m.checkin_b_id
             where m.theme_id = %s
             order by b.submitted_at_utc
            """,
            (theme["theme_id"],),
        )
    return themes


def generate_themes(
    conn: psycopg.Connection,
    session_id: str,
    clusterer: Clusterer | None = None,
    *,
    regenerate: bool = False,
) -> ThemeResult:
    """Cluster one session's muddiest-point answers.

    Existing themes are returned unchanged unless ``regenerate`` is set, so the
    console can show themes without spending an API call every page load. A
    regeneration **supersedes** rather than overwrites: the previous batch keeps
    its rows and gains a ``superseded_at``, because a teacher who planned a
    lesson around last week's themes should still be able to see what they read.
    """
    session = fetch_one(
        conn, 'select session_id, title from "session" where session_id = %s', (session_id,)
    )
    if session is None:
        raise LookupError(f"No session with id {session_id}")

    existing = current_themes(conn, session_id)
    if existing and not regenerate:
        return ThemeResult(
            session_id=session_id,
            themes=existing,
            answers_considered=sum(len(t["members"]) for t in existing),
            generated=False,
            message="showing the themes already generated; pass --regenerate to redo them",
        )

    rows = muddiest_answers(conn, session_id)
    texts = [str(row["rotating_text"]) for row in rows]

    if len(texts) < MIN_ANSWERS:
        return ThemeResult(
            session_id=session_id,
            themes=existing,
            answers_considered=len(texts),
            generated=False,
            message=(
                f"only {len(texts)} muddiest-point answer(s) for this session; "
                f"clustering needs at least {MIN_ANSWERS}. Read them directly — "
                "asking a model to find themes in three sentences produces themes "
                "that are not there."
            ),
        )

    clusterer = clusterer if clusterer is not None else build_clusterer()
    if clusterer is None:
        return ThemeResult(
            session_id=session_id,
            themes=existing,
            answers_considered=len(texts),
            generated=False,
            message=(
                "No GEMINI_API_KEY is set, so themes were not generated. The "
                f"{len(texts)} answers are stored and readable in full — clustering "
                "is a convenience over them, not a prerequisite for them."
            ),
        )

    try:
        drafts = clusterer.cluster(texts)
    except AiUnavailable as exc:
        # Degrade, never crash. The answers are the data; the themes are a view
        # over them.
        log.warning("theme clustering failed: %s", str(exc).splitlines()[0])
        return ThemeResult(
            session_id=session_id,
            themes=existing,
            answers_considered=len(texts),
            generated=False,
            message=f"Themes were not generated: {exc}",
        )

    superseded = execute(
        conn,
        """
        update muddiest_theme
           set superseded_at = now()
         where session_id = %s and superseded_at is null
        """,
        (session_id,),
    )

    for draft in drafts:
        theme_row = fetch_one(
            conn,
            """
            insert into muddiest_theme
                (session_id, label, summary, model, prompt_version)
            values (%s, %s, %s, %s, %s)
            returning theme_id
            """,
            (
                session_id,
                draft.label,
                draft.summary or "(no summary returned)",
                clusterer.model_name,
                getattr(clusterer, "prompt_version", PROMPT_VERSION),
            ),
        )
        assert theme_row is not None
        for number in draft.answer_numbers:
            execute(
                conn,
                """
                insert into muddiest_theme_member (theme_id, checkin_b_id)
                values (%s, %s)
                on conflict do nothing
                """,
                (theme_row["theme_id"], rows[number - 1]["checkin_b_id"]),
            )

    log.info(
        "themes generated session=%s themes=%d answers=%d superseded=%d",
        session_id,
        len(drafts),
        len(texts),
        superseded,
    )
    return ThemeResult(
        session_id=session_id,
        themes=current_themes(conn, session_id),
        answers_considered=len(texts),
        generated=True,
        superseded=superseded,
        message=f"{len(drafts)} theme(s) from {len(texts)} answer(s)",
    )


__all__ = [
    "MAX_THEMES",
    "MIN_ANSWERS",
    "MIN_THEMES",
    "PROMPT_VERSION",
    "RESPONSE_SCHEMA",
    "Clusterer",
    "GeminiClusterer",
    "ThemeDraft",
    "ThemeResult",
    "build_clusterer",
    "build_prompt",
    "current_themes",
    "generate_themes",
    "muddiest_answers",
    "parse_themes",
]
