// Real psql output from the demo database (postgresql://…:64322/cufa_demo_pa),
// captured 2026-09-25. Trimmed with … where long; nothing else is edited.
// Statements that write ran inside BEGIN … ROLLBACK, so no data changed.
export const ID_A = "be2264fd-a016-4ae9-8006-0ffb28fa5f9e"; // Jessamy Junipero, Session 1
export const ID_B = "c45e77c5-886b-4fc6-967b-47383711f107"; // Lorne Larkspur, CSV row that needs review
export const COUNTS = "      table_name      | rows \n----------------------+------\n cohort               |    1\n fellow               |   20\n session              |   12\n form_template        |    2\n session_form         |   22\n part_a_question_set  |    4\n part_a_form_question |   95\n checkin              |  103\n checkin_b            |   82\n slack_event          |    0\n attendance_decision  |  103\n help_request         |    2\n peer_shoutout        |  111\n assignment           |    0\n intervention         |    0\n bot_delivery         |    0\n(16 rows)";
export const RESOLVED = "     full_name     |            session_title            | in_window | answered |  status  |        rule_name         \n-------------------+-------------------------------------+-----------+----------+----------+--------------------------\n Jessamy Junipero  | Session 1 — What a civic problem is | t         |        8 | attended | verified_email_in_window\n Ardith Aldergrove | Session 1 — What a civic problem is | t         |        8 | attended | verified_email_in_window\n Bexley Brambleton | Session 1 — What a civic problem is | t         |        7 | attended | verified_email_in_window\n Corvin Cinderwick | Session 1 — What a civic problem is | t         |        7 | attended | verified_email_in_window\n Delphine Dunmore  | Session 1 — What a civic problem is | t         |        8 | attended | verified_email_in_window\n(5 rows)";
export const IMMUTABLE = "BEGIN\nERROR:  checkin rows are immutable; only latency_seconds may be recomputed (checkin_id=be2264fd-a016-4ae9-8006-0ffb28fa5f9e)\nCONTEXT:  PL/pgSQL function checkin_reject_mutation() line 25 at RAISE\nROLLBACK";
export const OVERRIDE = "BEGIN\nUPDATE 1\nINSERT 0 1\n decided_by |    status    |          by_whom           | confidence | superseded \n------------+--------------+----------------------------+------------+------------\n rule       | needs_review | unverified_email_in_window |            | t\n human      | attended     | staff.demo@example.invalid |      1.000 | f\n(2 rows)\n\nROLLBACK";
export const GUARDS = "BEGIN\nERROR:  new row for relation \"attendance_decision\" violates check constraint \"decision_provenance_present\"\nDETAIL:  Failing row contains (299a23a6-455c-4bd0-8b1d-79923e03b9bf, c45e77c5-886b-4fc6-967b-47383711f107, t, attended, null, human, null, …).\nROLLBACK\nBEGIN\nERROR:  duplicate key value violates unique constraint \"attendance_decision_one_current\"\nDETAIL:  Key (checkin_id)=(c45e77c5-886b-4fc6-967b-47383711f107) already exists.\nROLLBACK";
export const QSETS = "            scope             | version |  source   |         created_by         | superseded | questions \n------------------------------+---------+-----------+----------------------------+------------+-----------\n (cohort default)             |       1 | seed_file | cli:root                   | t          |         8\n (cohort default)             |       2 | console   | staff.demo@example.invalid | f          |         8\n Intro to Civic Innovation    |       1 | console   | staff.demo@example.invalid | f          |         7\n Session 3 — Reading a budget |       1 | cli       | cli:root                   | f          |         8\n(4 rows)";
export const RAW = " question_id |                                                                    answer                                                                    \n-------------+----------------------------------------------------------------------------------------------------------------------------------------------\n q0000a      | {\"title\": \"First Name\", \"values\": [\"Jessamy\"]}\n q0000c      | {\"title\": \"Last Name\", \"values\": [\"Junipero\"]}\n q0000e      | {\"title\": \"How would you rate today's session?\", \"values\": [\"4\"]}\n q00010      | {\"title\": \"What was your biggest takeaway from Lesson 1?\", \"values\": [\"A civic problem is only a problem once you can say who it affects.\"]}\n(4 rows)";
export const ANSWER = " item_index |    question_key    |     kind     |                             answer_values                              | has_content \n------------+--------------------+--------------+------------------------------------------------------------------------+-------------\n          0 | q_first_name       | short_answer | {Jessamy}                                                              | t\n          1 | q_last_name        | short_answer | {Junipero}                                                             | t\n          2 | q_session_rating   | linear_scale | {4}                                                                    | t\n          3 | q_biggest_takeaway | paragraph    | {\"A civic problem is only a problem once you can say who it affects.\"} | t\n          4 | q_more_of          | paragraph    | {\"More time for questions at the end.\"}                                | t\n          5 | q_less_of          | paragraph    | {\"Nothing, the pace was fine.\"}                                        | t\n          6 | q_open_questions   | paragraph    | {\"What happens if the council just says no?\"}                          | t\n          7 | q_other_feedback   | paragraph    | {\"The audio cut out for a few minutes in the middle.\"}                 | t\n(8 rows)";
export const HELP = " count \n-------\n     0\n(1 row)\n\n anon_reads | signed_in_reads \n------------+-----------------\n f          | f\n(1 row)";
export const SLACK_D = "                              Table \"public.slack_event\"\n     Column      |           Type           | Collation | Nullable |      Default      \n-----------------+--------------------------+-----------+----------+-------------------\n …\n event_type      | text                     |           | not null | \n channel_id      | text                     |           |          | \n channel_type    | text                     |           |          | \n slack_user_id   | text                     |           |          | \n user_email      | text                     |           |          | \n …\n text_length     | integer                  |           |          | \n word_count      | integer                  |           |          | \n has_link        | boolean                  |           |          | \n has_attachment  | boolean                  |           |          | \n text            | text                     |           |          | \n event_time_utc  | timestamp with time zone |           | not null | \n …\nPolicies:\n    POLICY \"slack_event_read_todo\" FOR SELECT\n      TO authenticated\n      USING (false)\nTriggers:\n    slack_event_no_mutation BEFORE DELETE OR UPDATE ON slack_event …";
export const SLACK_C = "Immutable observation of one act in Slack: a message, an edit, a deletion, a reaction, a join. Stores the EMAIL, not a fellow_id. Text is NULL by default — the participation definition counts acts, it does not read them.";
export const SLACK_N = " count \n-------\n     0\n(1 row)";
export const COUNTED = "    question_key    | answered | responses \n--------------------+----------+-----------\n q_first_name       |       11 |        11\n q_last_name        |       11 |        11\n q_biggest_takeaway |       11 |        11\n q_session_rating   |       11 |        11\n q_budget_parts     |        8 |        11\n q_more_of          |       11 |        11\n q_open_questions   |       11 |        11\n q_other_feedback   |        7 |        11\n(8 rows)";
export const COUNTED_C = "Part A answers, one row per (check-in, question), resolved through part_a_form_question at read time. answer_values keeps multi-select answers as separate values. For display and counting only — nothing here is scored.";
export const RLS = "     table_name      | rls_on \n---------------------+--------\n attendance_decision | t\n checkin             | t\n checkin_b           | t\n fellow              | t\n help_request        | t\n peer_shoutout       | t\n slack_event         | t\n(7 rows)";
export const POLICIES = "      tablename      |          policyname           |      roles      | qual  \n---------------------+-------------------------------+-----------------+-------\n attendance_decision | attendance_decision_read_todo | {authenticated} | false\n checkin             | checkin_read_todo             | {authenticated} | false\n fellow              | fellow_read_todo              | {authenticated} | false\n(3 rows)";
// From the console on :8200 against the same database.
export const EXPORT = "fellow_id,full_name,status,messages,messages_7d,words,cohort_mean_messages,slack_share,sessions_held,attended,needs_review,attendance_rate,forms_submi\nCU-2617,Rosalind Ravensmoor,active,0,0,0,0.0,,10,0,0,0.0,5,10,0.933,71,missing sessions,False,0,\nCU-2618,Sabra Stonebrook,active,0,0,0,0.0,,10,4,0,0.4,0,10,,60,missing sessions,False,0,\nCU-2619,Marisol Thornbury,active,0,0,0,0.0,,10,3,0,0.3,8,10,0.875,52,missing sessions,False,0,";
export const EXPORT_HELP = "0";
