/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/classroomTheme.js
 * Command: astryx theme build src/theme/classroomTheme.js
 * CLI: @astryxdesign/cli@0.4.7
 * Core: @astryxdesign/core@0.4.7
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Text' {
  interface TextColorMap {
    'progress': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
