/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/classroomTheme.js
 * Command: astryx theme build src/theme/classroomTheme.js
 * CLI: @astryxdesign/cli@0.4.7
 * Core: @astryxdesign/core@0.4.7
 */

/// <reference path="./classroom.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const classroomIcons: IconRegistry;
export declare const classroomTheme: DefinedTheme;
