/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/classroomTheme.js
 * Command: astryx theme build src/theme/classroomTheme.js
 * CLI: @astryxdesign/cli@0.4.7
 * Core: @astryxdesign/core@0.4.7
 */

import { classroomIcons } from './icons.js';
/**
 * classroom theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { classroomTheme } from './classroom';
 *   import './classroom.css';
 */
export const classroomTheme = {
  name: 'classroom',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.6875rem",
    "--font-size-sm": "0.875rem",
    "--font-size-base": "1.0625rem",
    "--font-size-lg": "1.3125rem",
    "--font-size-xl": "1.6875rem",
    "--font-size-2xl": "2.0625rem",
    "--font-size-3xl": "2.625rem",
    "--font-size-4xl": "3.25rem",
    "--font-size-5xl": "4.0625rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": 700,
    "--text-heading-1-leading": "1.2121",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": 700,
    "--text-heading-2-leading": "1.3333",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": 700,
    "--text-heading-3-leading": "1.3333",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": 700,
    "--text-heading-4-leading": "1.4118",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": 700,
    "--text-heading-5-leading": "1.4286",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": 700,
    "--text-heading-6-leading": "1.4545",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": 400,
    "--text-body-leading": "1.4118",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.3333",
    "--text-label-size": "15px",
    "--text-label-weight": "600",
    "--text-label-leading": "1.4118",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4118",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.4286",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "800",
    "--text-display-1-leading": "1.2308",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "800",
    "--text-display-2-leading": "1.2308",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "800",
    "--text-display-3-leading": "1.2381",
    "--duration-fast-min": "95ms",
    "--duration-fast": "125ms",
    "--duration-fast-max": "165ms",
    "--duration-medium-min": "225ms",
    "--duration-medium": "300ms",
    "--duration-medium-max": "400ms",
    "--duration-slow-min": "525ms",
    "--duration-slow": "700ms",
    "--duration-slow-max": "935ms",
    "--font-family-body": "\"Nunito Sans Variable\", \"Nunito Sans\", \"Segoe UI\", system-ui, -apple-system, sans-serif",
    "--font-family-heading": "\"Nunito Variable\", Nunito, ui-rounded, \"SF Pro Rounded\", system-ui, sans-serif",
    "--font-family-code": "ui-monospace, \"SF Mono\", Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
    "--color-syntax-keyword": "light-dark(#700084, #efa8ff)",
    "--color-syntax-string": "light-dark(#005600, #a6d2a2)",
    "--color-syntax-comment": "light-dark(#737373, #a3a3a3)",
    "--color-syntax-number": "light-dark(#6e3500, #ffb37f)",
    "--color-syntax-function": "light-dark(#00458c, #a0caff)",
    "--color-syntax-type": "light-dark(#700084, #efa8ff)",
    "--color-syntax-variable": "light-dark(#171717, #e5e5e5)",
    "--color-syntax-operator": "light-dark(#737373, #a3a3a3)",
    "--color-syntax-constant": "light-dark(#6e3500, #ffb37f)",
    "--color-syntax-tag": "light-dark(#89001a, #ffaeaa)",
    "--color-syntax-attribute": "light-dark(#584400, #eec12f)",
    "--color-syntax-property": "light-dark(#005348, #83dac9)",
    "--color-syntax-punctuation": "light-dark(#a3a3a3, #525252)",
    "--color-syntax-background": "light-dark(#fafafa, #0a0a0a)",
    "--color-background-surface": "#ffffff",
    "--color-background-body": "#ffffff",
    "--color-background-card": "#ffffff",
    "--color-background-popover": "#ffffff",
    "--color-background-muted": "#f7f7f7",
    "--color-accent": "#58cc02",
    "--color-accent-muted": "#d7ffb8",
    "--color-neutral": "#4b4b4b0d",
    "--color-overlay": "#4b4b4b80",
    "--color-overlay-hover": "#00000010",
    "--color-overlay-pressed": "#0000001f",
    "--color-text-primary": "#4b4b4b",
    "--color-text-secondary": "#777777",
    "--color-text-disabled": "#afafaf",
    "--color-text-accent": "#077db5",
    "--color-on-dark": "#ffffff",
    "--color-on-light": "#4b4b4b",
    "--color-on-accent": "#ffffff",
    "--color-on-success": "#3d7000",
    "--color-on-error": "#a62828",
    "--color-on-warning": "#8a5200",
    "--color-icon-accent": "#077db5",
    "--color-icon-primary": "#4b4b4b",
    "--color-icon-secondary": "#777777",
    "--color-icon-disabled": "#afafaf",
    "--color-success": "#58cc02",
    "--color-error": "#ff4b4b",
    "--color-warning": "#ffc800",
    "--color-success-muted": "#d7ffb8",
    "--color-error-muted": "#ffe0e0",
    "--color-warning-muted": "#fff3cc",
    "--color-border": "#e5e5e5",
    "--color-border-emphasized": "#afafaf",
    "--color-skeleton": "#efefef",
    "--color-shadow": "#00000000",
    "--color-tint-hover": "#58cc02",
    "--color-background-red": "#ffe0e0",
    "--color-border-red": "#ffb3b3",
    "--color-icon-red": "#a62828",
    "--color-text-red": "#a62828",
    "--color-background-orange": "#ffe9c9",
    "--color-border-orange": "#ffc06e",
    "--color-icon-orange": "#8a5200",
    "--color-text-orange": "#8a5200",
    "--color-background-yellow": "#fff3cc",
    "--color-border-yellow": "#ffc800",
    "--color-icon-yellow": "#8a5200",
    "--color-text-yellow": "#8a5200",
    "--color-background-green": "#d7ffb8",
    "--color-border-green": "#a5ed6e",
    "--color-icon-green": "#3d7000",
    "--color-text-green": "#3d7000",
    "--color-background-teal": "#d6f5ec",
    "--color-border-teal": "#8fe3cd",
    "--color-icon-teal": "#00695c",
    "--color-text-teal": "#00695c",
    "--color-background-cyan": "#d9f4fb",
    "--color-border-cyan": "#8fdcee",
    "--color-icon-cyan": "#00607a",
    "--color-text-cyan": "#00607a",
    "--color-background-blue": "#ddf4ff",
    "--color-border-blue": "#9adcfb",
    "--color-icon-blue": "#00679c",
    "--color-text-blue": "#00679c",
    "--color-background-purple": "#ece2ff",
    "--color-border-purple": "#c3a9ff",
    "--color-icon-purple": "#5b3fa8",
    "--color-text-purple": "#5b3fa8",
    "--color-background-pink": "#ffe1ef",
    "--color-border-pink": "#ffaed0",
    "--color-icon-pink": "#a32663",
    "--color-text-pink": "#a32663",
    "--color-background-gray": "#f2f2f2",
    "--color-border-gray": "#e5e5e5",
    "--color-icon-gray": "#777777",
    "--color-text-gray": "#777777",
    "--radius-none": "0px",
    "--radius-inner": "12px",
    "--radius-element": "12px",
    "--radius-container": "16px",
    "--radius-page": "16px",
    "--radius-full": "9999px",
    "--shadow-low": "none",
    "--shadow-med": "none",
    "--shadow-high": "none",
    "--shadow-inset-hover": "inset 0 0 0 2px #58cc0233",
    "--shadow-inset-selected": "inset 0 0 0 2px #58cc0280",
    "--shadow-inset-success": "inset 0 0 0 2px #58cc0280",
    "--shadow-inset-warning": "inset 0 0 0 2px #ffc80080",
    "--shadow-inset-error": "inset 0 0 0 2px #ff4b4b80",
    "--radius-chat": "28px",
    "--color-background-inverted": "#4b4b4b",
    "--font-weight-medium": "600",
    "--font-weight-semibold": "700",
    "--font-weight-bold": "700",
    "--section-heading-ink": "#3a8701",
    "--accent-bevel": "#46a302",
    "--size-element-sm": "32px",
    "--size-element-md": "40px",
    "--size-element-lg": "48px"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "base": {
        "letterSpacing": "-0.02em",
        "--color-accent": "var(--section-heading-ink)"
      },
      "color:progress": {
        "color": "#3a8701"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "variant:destructive": {
        "backgroundColor": "var(--color-error-muted)",
        "color": "var(--color-error)",
        "::after": {
          "content": "\"\"",
          "position": "absolute",
          "insetInlineStart": "0",
          "insetInlineEnd": "0",
          "top": "100%",
          "height": "4px",
          "backgroundColor": "#e03d3d",
          "borderEndStartRadius": "12px",
          "borderEndEndRadius": "12px",
          "pointerEvents": "none"
        },
        ":active": {
          "translate": "0 4px"
        },
        ":active::after": {
          "height": "0px"
        }
      },
      "base": {
        "borderRadius": "12px",
        "textTransform": "uppercase",
        "letterSpacing": "0.053em"
      },
      "variant:primary": {
        "::after": {
          "content": "\"\"",
          "position": "absolute",
          "insetInlineStart": "0",
          "insetInlineEnd": "0",
          "top": "100%",
          "height": "4px",
          "backgroundColor": "var(--accent-bevel)",
          "borderEndStartRadius": "12px",
          "borderEndEndRadius": "12px",
          "pointerEvents": "none"
        },
        ":active": {
          "translate": "0 4px"
        },
        ":active::after": {
          "height": "0px"
        }
      },
      "variant:secondary": {
        "--color-neutral": "#ffffff",
        "--color-text-primary": "#077db5",
        "--color-icon-primary": "#077db5",
        "::before": {
          "content": "\"\"",
          "position": "absolute",
          "inset": "0",
          "borderRadius": "inherit",
          "borderWidth": "1px",
          "borderStyle": "solid",
          "borderColor": "#777777",
          "pointerEvents": "none"
        }
      },
      "variant:ghost": {}
    },
    "badge": {
      "variant:info": {
        "backgroundColor": "light-dark(#0074e2, #6d9cfe)",
        "color": "light-dark(#ffffff, #171717)"
      },
      "variant:neutral": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      },
      "variant:success": {
        "backgroundColor": "light-dark(#198100, #64af4c)",
        "color": "light-dark(#ffffff, #171717)"
      },
      "variant:warning": {
        "backgroundColor": "#ffce2f",
        "color": "#171717"
      },
      "variant:error": {
        "backgroundColor": "light-dark(#e33f4a, #ff705d)",
        "color": "light-dark(#ffffff, #171717)"
      },
      "variant:red": {
        "backgroundColor": "var(--color-background-red)",
        "color": "var(--color-text-red)"
      },
      "variant:orange": {
        "backgroundColor": "var(--color-background-orange)",
        "color": "var(--color-text-orange)"
      },
      "variant:yellow": {
        "backgroundColor": "var(--color-background-yellow)",
        "color": "var(--color-text-yellow)"
      },
      "variant:green": {
        "backgroundColor": "var(--color-background-green)",
        "color": "var(--color-text-green)"
      },
      "variant:teal": {
        "backgroundColor": "var(--color-background-teal)",
        "color": "var(--color-text-teal)"
      },
      "variant:cyan": {
        "backgroundColor": "var(--color-background-cyan)",
        "color": "var(--color-text-cyan)"
      },
      "variant:blue": {
        "backgroundColor": "var(--color-background-blue)",
        "color": "var(--color-text-blue)"
      },
      "variant:purple": {
        "backgroundColor": "var(--color-background-purple)",
        "color": "var(--color-text-purple)"
      },
      "variant:pink": {
        "backgroundColor": "var(--color-background-pink)",
        "color": "var(--color-text-pink)"
      },
      "variant:gray": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      },
      "base": {
        "--radius-inner": "12px",
        "--font-weight-medium": "600"
      }
    },
    "statusdot": {
      "variant:success": {
        "backgroundColor": "light-dark(#198100, #64af4c)"
      },
      "variant:warning": {
        "backgroundColor": "#ffce2f"
      },
      "variant:error": {
        "backgroundColor": "light-dark(#e33f4a, #ff705d)"
      },
      "variant:accent": {
        "backgroundColor": "light-dark(#0074e2, #6d9cfe)"
      }
    },
    "banner": {
      "status:info": {
        "--color-accent-muted": "var(--color-background-blue)",
        "--color-text-primary": "var(--color-text-blue)",
        "--color-text-secondary": "var(--color-text-blue)",
        "--color-accent": "var(--color-text-blue)"
      },
      "status:success": {
        "--color-text-primary": "var(--color-text-green)",
        "--color-text-secondary": "var(--color-text-green)",
        "--color-success": "var(--color-text-green)"
      },
      "status:warning": {
        "--color-text-primary": "var(--color-text-yellow)",
        "--color-text-secondary": "var(--color-text-yellow)",
        "--color-warning": "var(--color-text-yellow)"
      },
      "status:error": {
        "--color-text-primary": "var(--color-text-red)",
        "--color-text-secondary": "var(--color-text-red)",
        "--color-error": "var(--color-text-red)"
      },
      "base": {
        "borderRadius": "16px",
        "--border-width": "1px"
      }
    },
    "switch": {
      "base": {
        "--color-background-gray": "var(--color-border-emphasized)"
      }
    },
    "progressbar": {
      "base": {
        "--color-background-muted": "var(--color-border-emphasized)",
        "--font-weight-medium": "600",
        "--font-weight-normal": "500"
      },
      "variant:accent": {
        "--color-accent": "#0074e2"
      },
      "variant:success": {
        "--color-success": "#198100"
      },
      "variant:warning": {
        "--color-warning": "#ffce2f"
      },
      "variant:error": {
        "--color-error": "#e33f4a"
      }
    },
    "card": {
      "base": {
        "padding": "20px",
        "borderRadius": "16px",
        "--border-width": "0px"
      },
      "variant:lead-green": {
        "backgroundColor": "#3a8701",
        "color": "#ffffff",
        "--color-text-primary": "#ffffff",
        "--color-text-secondary": "#ffffff",
        "--color-text-disabled": "rgba(255,255,255,0.62)",
        "--color-text-accent": "#ffffff",
        "--color-icon-primary": "#ffffff",
        "--color-icon-secondary": "#ffffff",
        "--color-icon-accent": "#ffffff",
        "--color-on-light": "#ffffff",
        "--color-accent": "#ffffff",
        "--color-on-accent": "#3a8701",
        "--section-heading-ink": "#ffffff",
        "--accent-bevel": "rgba(0,0,0,0.22)",
        "--color-neutral": "rgba(255,255,255,0.18)",
        "--color-border": "rgba(255,255,255,0.32)",
        "--color-overlay-hover": "rgba(255,255,255,0.12)",
        "--color-overlay-pressed": "rgba(255,255,255,0.22)"
      },
      "variant:lead-blue": {
        "backgroundColor": "#077db5",
        "color": "#ffffff",
        "--color-text-primary": "#ffffff",
        "--color-text-secondary": "#ffffff",
        "--color-text-disabled": "rgba(255,255,255,0.62)",
        "--color-text-accent": "#ffffff",
        "--color-icon-primary": "#ffffff",
        "--color-icon-secondary": "#ffffff",
        "--color-icon-accent": "#ffffff",
        "--color-on-light": "#ffffff",
        "--color-accent": "#ffffff",
        "--color-on-accent": "#077db5",
        "--section-heading-ink": "#ffffff",
        "--accent-bevel": "rgba(0,0,0,0.22)",
        "--color-neutral": "rgba(255,255,255,0.18)",
        "--color-border": "rgba(255,255,255,0.32)",
        "--color-overlay-hover": "rgba(255,255,255,0.12)",
        "--color-overlay-pressed": "rgba(255,255,255,0.22)"
      },
      "variant:lead-purple": {
        "backgroundColor": "#9a4cee",
        "color": "#ffffff",
        "--color-text-primary": "#ffffff",
        "--color-text-secondary": "#ffffff",
        "--color-text-disabled": "rgba(255,255,255,0.62)",
        "--color-text-accent": "#ffffff",
        "--color-icon-primary": "#ffffff",
        "--color-icon-secondary": "#ffffff",
        "--color-icon-accent": "#ffffff",
        "--color-on-light": "#ffffff",
        "--color-accent": "#ffffff",
        "--color-on-accent": "#9a4cee",
        "--section-heading-ink": "#ffffff",
        "--accent-bevel": "rgba(0,0,0,0.22)",
        "--color-neutral": "rgba(255,255,255,0.18)",
        "--color-border": "rgba(255,255,255,0.32)",
        "--color-overlay-hover": "rgba(255,255,255,0.12)",
        "--color-overlay-pressed": "rgba(255,255,255,0.22)"
      },
      "variant:lead-orange": {
        "backgroundColor": "#b85c00",
        "color": "#ffffff",
        "--color-text-primary": "#ffffff",
        "--color-text-secondary": "#ffffff",
        "--color-text-disabled": "rgba(255,255,255,0.62)",
        "--color-text-accent": "#ffffff",
        "--color-icon-primary": "#ffffff",
        "--color-icon-secondary": "#ffffff",
        "--color-icon-accent": "#ffffff",
        "--color-on-light": "#ffffff",
        "--color-accent": "#ffffff",
        "--color-on-accent": "#b85c00",
        "--section-heading-ink": "#ffffff",
        "--accent-bevel": "rgba(0,0,0,0.22)",
        "--color-neutral": "rgba(255,255,255,0.18)",
        "--color-border": "rgba(255,255,255,0.32)",
        "--color-overlay-hover": "rgba(255,255,255,0.12)",
        "--color-overlay-pressed": "rgba(255,255,255,0.22)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)",
        "borderRadius": "16px"
      }
    },
    "text-input": {
      "base": {
        "borderRadius": "12px",
        "--border-width": "1px",
        "--color-border-emphasized": "#777777"
      }
    },
    "selector": {
      "base": {
        "borderRadius": "12px",
        "--border-width": "1px",
        "--color-border-emphasized": "#777777"
      }
    },
    "textarea": {
      "base": {
        "borderRadius": "12px",
        "--border-width": "1px",
        "--color-border-emphasized": "#777777"
      }
    },
    "field-label": {
      "base": {
        "--font-weight-medium": "600",
        "--color-text-secondary": "#777777"
      }
    },
    "token": {
      "base": {
        "--radius-inner": "12px",
        "--font-weight-medium": "600"
      }
    },
    "table-header-cell": {
      "base": {
        "--text-label-size": "13px",
        "--font-weight-semibold": "600",
        "--color-text-secondary": "#777777",
        "--border-width": "1px"
      }
    },
    "table-cell": {
      "base": {
        "--border-width": "1px"
      }
    },
    "divider": {
      "base": {
        "--border-width": "1px"
      }
    },
    "side-nav": {
      "base": {
        "backgroundColor": "#ffffff",
        "fontFamily": "var(--font-family-heading)",
        "borderInlineEndWidth": "1px",
        "borderInlineEndStyle": "solid",
        "borderInlineEndColor": "#e5e5e5"
      }
    },
    "side-nav-item": {
      "base": {
        "borderRadius": "12px",
        "--text-label-size": "15px",
        "--font-weight-normal": "600",
        "--color-text-primary": "#777777"
      },
      "selected": {
        "--color-neutral": "#d7ffb8",
        "--color-text-primary": "#3d7000",
        "--font-weight-medium": "700"
      }
    },
    "side-nav-heading": {
      "base": {
        "letterSpacing": "-0.01em",
        "--text-large-size": "17px",
        "--text-large-leading": "1.3",
        "--font-weight-semibold": "700",
        "--color-text-primary": "#4b4b4b"
      }
    },
    "side-nav-section": {
      "base": {
        "--text-supporting-size": "12px",
        "--font-weight-semibold": "700",
        "--color-text-secondary": "#777777"
      }
    },
    "top-nav": {
      "base": {
        "backgroundColor": "#ffffff",
        "fontFamily": "var(--font-family-heading)",
        "borderBottomWidth": "1px",
        "borderBottomStyle": "solid",
        "borderBottomColor": "#e5e5e5"
      }
    },
    "top-nav-item": {
      "base": {
        "borderRadius": "12px",
        "--text-label-size": "15px",
        "--font-weight-normal": "600",
        "--color-text-primary": "#777777"
      },
      "selected": {
        "--color-neutral": "#d7ffb8",
        "--color-text-primary": "#3d7000"
      }
    },
    "top-nav-heading": {
      "base": {
        "--font-weight-semibold": "700"
      }
    },
    "progressbar-track": {
      "base": {
        "minHeight": "16px",
        "--color-background-muted": "#e5e5e5"
      }
    },
    "progressbar-fill": {
      "base": {
        "--color-accent": "#58cc02"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  icons: classroomIcons,
};

export { classroomIcons };
